### ISSUE TITLE
Image is broken

### ISSUE THREAD

**Issue by Ryonez** [Pe46dro/XBackBone-docker#3]
**System Info**
Latest docker image

**Describe the bug**
xbackbone works fine until the docker is stopped. After it's stopped, it never comes back up.

**To Reproduce**
1. Install docker image
2. Run it
3. Stop it
4. start it

**Expected behavior**
To start up again

**Screenshots**
From the log:
![image](https://user-images.githubusercontent.com/16157130/56175156-f329e900-6049-11e9-9ce4-18b2d672ad18.png)

**Comment by stilesdev** [comment]
I'm seeing the same issue:
```
2019-05-08 05:05:47,296 INFO stopped: syslogd (exit status 0)
error: failed switching to "root": operation not permitted
```

**Comment by Pe46dro** [comment]
The issue seems to be related to https://github.com/webdevops/Dockerfile/issues/226
I will investigate further and i will try to release a fix in next few days

**Comment by Pe46dro** [comment]
Fixed in c5a3d3842b0d4c8c87db8a94a1e54b9a20f75313
To apply the fix update to latest release
I also added a test in CI pipeline

**Comment by Kombustor** [comment]
This still happens in version 2.5.3 for me, so bump (@Pe46dro)

After a seemingly random amount of time, the console is getting spammed with `error: failed switching to "root": operation not permitted` and the app stops working.

**Comment by Pe46dro** [comment]
@Kombustor i tried with a fresh pull in a new server and I can't replicate the problem.
```
# docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS
fbd901eed819        pe46dro/xbackbone-docker                 "/entrypoint super..."   12 days ago         Up 12 days

# docker restart fbd901eed819
fbd901eed819

# docker ps
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS
fbd901eed819        pe46dro/xbackbone-docker                 "/entrypoint super..."   12 days ago         Up 1 second
```

**Comment by ranasats** [comment]
This is happening on my build as well, randomly started giving this error.
